{
 "title": "Tezos",
 "tags": [
  "blockchain",
  "tezos",
  "summary"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "prometheus" },
   {
    "name": "release",
    "label": "Release",
    "query": "label_values(up{app=\"tezos-node\"}, release)"
   }
  ]
 },
 "panels": [
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tezos_node_peers{release=\"$release\",state=\"disconnected\",trusted=\"false\"}",
     "legendFormat": "Disconnected peers"
    },
    {
     "expr": "tezos_node_peers{release=\"$release\",state=\"running\",trusted=\"false\"}",
     "legendFormat": "Running peers"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tezos_node_connections{direction=\"incoming\",private=\"false\",release=\"$release\"}",
     "legendFormat": "Incoming public"
    },
    {
     "expr": "tezos_node_connections{direction=\"incoming\",private=\"true\",release=\"$release\"}",
     "legendFormat": "Incoming private"
    },
    {
     "expr": "tezos_node_connections{direction=\"outgoing\",private=\"false\",release=\"$release\"}",
     "legendFormat": "Outgoing public"
    },
    {
     "expr": "tezos_node_connections{direction=\"outgoing\",private=\"true\",release=\"$release\"}",
     "legendFormat": "Outgoing private"
    }
   ]
  },
  {
   "title": "Received\\Send total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tezos_node_recv_bytes_total", "legendFormat": "Recived bytes" },
    { "expr": "tezos_node_sent_bytes_total", "legendFormat": "Sent bytes" }
   ]
  },
  {
   "title": "RCP failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tezos_rpc_failed{release=\"$release\",rpc=\"/network/connections\"}",
     "legendFormat": "/network/connections"
    },
    {
     "expr": "tezos_rpc_failed{release=\"$release\",rpc=\"/network/peers\"}",
     "legendFormat": "/network/peers"
    },
    {
     "expr": "tezos_rpc_failed{release=\"$release\",rpc=\"/network/points\"}",
     "legendFormat": "/network/points"
    },
    {
     "expr": "tezos_rpc_failed{release=\"$release\",rpc=\"/network/stat\"}",
     "legendFormat": "/network/stat"
    }
   ]
  },
  {
   "title": "Points",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tezos_node_points{release=\"$release\",event_kind=\"disconnected\",trusted=\"false\"}",
     "legendFormat": "Disconnected untrusted"
    },
    {
     "expr": "tezos_node_points{release=\"$release\",event_kind=\"disconnected\",trusted=\"true\"}",
     "legendFormat": "Disconnected trusted"
    },
    {
     "expr": "tezos_node_points{release=\"$release\",event_kind=\"running\",trusted=\"false\"}",
     "legendFormat": "Running untrusted"
    },
    {
     "expr": "tezos_node_points{release=\"$release\",event_kind=\"running\",trusted=\"true\"}",
     "legendFormat": "Running trusted"
    }
   ]
  },
  {
   "title": "Node bootstraped",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "tezos_node_bootstrapped{release=\"$release\"}",
     "legendFormat": "$release"
    }
   ]
  }
 ]
}